/*
* Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
*
* NVIDIA CORPORATION and its licensors retain all intellectual property
* and proprietary rights in and to this software, related documentation
* and any modifications thereto.  Any use, reproduction, disclosure or
* distribution of this software and related documentation without an express
* license agreement from NVIDIA CORPORATION is strictly prohibited.
*/

 #ifndef __TONE_MAPPING_PS_HLSLI__ // using instead of "#pragma once" due to https://github.com/microsoft/DirectXShaderCompiler/issues/3943
 #define __TONE_MAPPING_PS_HLSLI__

#include "ToneMapping_cb.h"

SamplerState gLuminanceTexSampler : register(s0);
SamplerState gColorSampler : register(s1);

Texture2D gColorTex : register(t0);
Texture2D gLuminanceTex : register(t1);

//static const uint kOperator = _TONE_MAPPER_OPERATOR;
static const float kExposureKey = TONEMAPPING_EXPOSURE_KEY;
static const float kLuminanceLod = 16.0; // Lookup highest mip level to get average luminance

cbuffer PerImageCB : register(b0)
{
    ToneMappingConstants gParams;
};

float calcLuminance(float3 color)
{
    return dot(color, float3(0.299, 0.587, 0.114));
}

// Linear
float3 toneMapLinear(float3 color)
{
    return color;
}

// Reinhard
float3 toneMapReinhard(float3 color)
{
    float luminance = calcLuminance(color);
    // Algebraically equivalent to luminance/(luminance+1), but avoids the
    // 0/0 generated by perfectly black pixels and preserves chromaticity.
    return color / (luminance + 1.0);
}

// Reinhard with maximum luminance
float3 toneMapReinhardModified(float3 color)
{
    float luminance = calcLuminance(color);
    float whiteLuminanceSq = max(gParams.whiteMaxLuminance * gParams.whiteMaxLuminance, 1e-6);

    // Ld = L * (1 + L / Lwhite^2) / (1 + L). Applying Ld / L to
    // RGB preserves chromaticity; writing the scale directly also avoids 0/0
    // for perfectly black pixels.
    float scale = (1.0 + luminance / whiteLuminanceSq) / (1.0 + luminance);
    return color * scale;
}

// John Hable's ALU approximation of Jim Heji's operator
// http://filmicgames.com/archives/75
float3 toneMapHejiHableAlu(float3 color)
{
    color = max(float(0).rrr, color - 0.004);
    color = (color*(6.2 * color + 0.5)) / (color * (6.2 * color + 1.7) + 0.06);

    // Result includes sRGB conversion
    return pow(color, float3(2.2, 2.2, 2.2));
}

// John Hable's Uncharted 2 filmic tone map
// http://filmicgames.com/archives/75
float3 applyUc2Curve(float3 color)
{
    float A = 0.22; // Shoulder Strength
    float B = 0.3;  // Linear Strength
    float C = 0.1;  // Linear Angle
    float D = 0.2;  // Toe Strength
    float E = 0.01; // Toe Numerator
    float F = 0.3;  // Toe Denominator

    color = ((color * (A*color+C*B)+D*E)/(color*(A*color+B)+D*F))-(E/F);
    return color;
}

float3 toneMapHableUc2(float3 color)
{
    float exposureBias = 2.0f;
    color = applyUc2Curve(exposureBias * color);
    float whiteScale = 1 / applyUc2Curve(float3(gParams.whiteScale, gParams.whiteScale, gParams.whiteScale)).x;
    color = color * whiteScale;

    return color;
}

float3 toneMapAces(float3 color)
{
    // Cancel out the pre-exposure mentioned in
    // https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve/
    color *= 0.6;

    float A = 2.51;
    float B = 0.03;
    float C = 2.43;
    float D = 0.59;
    float E = 0.14;

    color = saturate((color*(A*color+B))/(color*(C*color+D)+E));
    return color;
}

// Khronos PBR Neutral, for non-negative Linear Rec.709 input and output.
// Specification: https://github.com/KhronosGroup/ToneMapping/tree/main/PBR_Neutral
float3 toneMapPbrNeutral(float3 color)
{
    const float startCompression = 0.8 - 0.04;
    const float desaturation = 0.15;

    // The specification assumes non-negative radiance. Denoising and temporal
    // reconstruction can produce small negative values, so enforce that
    // precondition before evaluating the curve.
    color = max(color, 0.0.xxx);

    float x = min(color.r, min(color.g, color.b));
    float offset = (x < 0.08) ? (x - 6.25 * x * x) : 0.04;
    color -= offset;

    float peak = max(color.r, max(color.g, color.b));
    if (peak < startCompression)
        return color;

    const float d = 1.0 - startCompression;
    float newPeak = 1.0 - d * d / (peak + d - startCompression);
    color *= newPeak / peak;

    float g = 1.0 - 1.0 / (desaturation * (peak - newPeak) + 1.0);
    return lerp(color, newPeak.xxx, g);
}

// Leaves photographic low/mid tones exactly unchanged and compresses only
// values above a configurable peak threshold. The exponential branch joins
// the identity branch with matching value and first derivative. Scaling RGB
// by the mapped peak preserves hue and guarantees a bounded non-negative
// result for non-negative input.
float3 toneMapPhotoSoftShoulder(float3 color)
{
    color = max(color, 0.0.xxx);

    float peak = max(color.r, max(color.g, color.b));
    float start = clamp(gParams.photoSoftShoulderStart, 0.0, 0.999);
    if (peak <= start)
        return color;

    float range = 1.0 - start;
    float mappedPeak = start + range * (1.0 - exp(-(peak - start) / range));
    return color * (mappedPeak / peak);
}

// Real-time AgX approximation used by Filament/Three.js, based on Blender's
// AgX view transform. Input and output are scene-linear Rec.709/sRGB primaries.
float3 agxDefaultContrastApprox(float3 x)
{
    float3 x2 = x * x;
    float3 x4 = x2 * x2;
    return 15.5 * x4 * x2
        - 40.14 * x4 * x
        + 31.96 * x4
        - 6.868 * x2 * x
        + 0.4298 * x2
        + 0.1191 * x
        - 0.00232;
}

float3 toneMapAgx(float3 color)
{
    const float minEv = -12.47393;
    const float maxEv = 4.026069;

    // Spell out the row dot-products. This avoids backend-dependent matrix
    // packing/transpose behavior between DXIL and SPIR-V for local matrices.
    color = max(color, 0.0.xxx);
    color = float3(
        dot(color, float3(0.6274, 0.3293, 0.0433)),
        dot(color, float3(0.0691, 0.9195, 0.0113)),
        dot(color, float3(0.0164, 0.0880, 0.8956)));
    color = float3(
        dot(color, float3(0.8566271533, 0.0951212405, 0.0482516061)),
        dot(color, float3(0.1373189729, 0.7612419906, 0.1014390365)),
        dot(color, float3(0.1118982130, 0.0767994186, 0.8113023684)));
    color = saturate((log2(max(color, 1e-10.xxx)) - minEv) / (maxEv - minEv));
    color = agxDefaultContrastApprox(color);
    color = float3(
        dot(color, float3( 1.1271005818, -0.1106066431, -0.0164939387)),
        dot(color, float3(-0.1413297635,  1.1578237022, -0.0164939387)),
        dot(color, float3(-0.1413297635, -0.1106066431,  1.2519364066)));

    // The fitted contrast curve produces a gamma-domain value. Return it to
    // linear light because the output framebuffer performs sRGB encoding.
    color = pow(max(color, 0.0.xxx), 2.2.xxx);
    color = float3(
        dot(color, float3( 1.6605, -0.5876, -0.0728)),
        dot(color, float3(-0.1246,  1.1329, -0.0083)),
        dot(color, float3(-0.0182, -0.1006,  1.1187)));
    return saturate(color);
}

// Calibrated camera-response LUT. The .cube loader resamples every curve to
// TONEMAPPING_CAMERA_LUT_SIZE entries and stores linear-light output values.
float3 toneMapCameraLut(float3 color)
{
    float3 domainRange = max(gParams.cameraLutDomainMax - gParams.cameraLutDomainMin, 1e-6.xxx);
    float3 position = saturate((color - gParams.cameraLutDomainMin) / domainRange)
        * float(TONEMAPPING_CAMERA_LUT_SIZE - 1);
    uint3 lower = (uint3)floor(position);
    uint3 upper = min(lower + 1, uint3(TONEMAPPING_CAMERA_LUT_SIZE - 1,
        TONEMAPPING_CAMERA_LUT_SIZE - 1, TONEMAPPING_CAMERA_LUT_SIZE - 1));
    float3 fraction = frac(position);

    float3 low = float3(
        gParams.cameraLut[lower.x].r,
        gParams.cameraLut[lower.y].g,
        gParams.cameraLut[lower.z].b);
    float3 high = float3(
        gParams.cameraLut[upper.x].r,
        gParams.cameraLut[upper.y].g,
        gParams.cameraLut[upper.z].b);
    return lerp(low, high, fraction);
}

float3 toneMap(float3 color)
{
    switch ((ToneMapperOperator)gParams.toneMapOperator)
    {
        case ToneMapperOperator::Linear:
            return toneMapLinear(color);
        case ToneMapperOperator::Reinhard:
            return toneMapReinhard(color);
        case ToneMapperOperator::ReinhardModified:
            return toneMapReinhardModified(color);
        case ToneMapperOperator::HejiHableAlu:
            return toneMapHejiHableAlu(color);
        case ToneMapperOperator::HableUc2:
            return toneMapHableUc2(color);
        case ToneMapperOperator::Aces:
            return toneMapAces(color);
        case ToneMapperOperator::PbrNeutral:
            return toneMapPbrNeutral(color);
        case ToneMapperOperator::PhotoSoftShoulder:
            return toneMapPhotoSoftShoulder(color);
        case ToneMapperOperator::Agx:
            return toneMapAgx(color);
        case ToneMapperOperator::CameraLut:
            return toneMapCameraLut(color);
        default:
            return color;
    }
}

//Renamed main function 
//float4 main(float2 texC : TEXCOORD) : SV_TARGET0
float4 applyToneMapping(float2 texC)
{
    float4 color = gColorTex.Sample(gColorSampler, texC);
    float3 finalColor = color.rgb;
/*
#ifdef _TONE_MAPPER_AUTO_EXPOSURE
    // apply auto exposure
    float avgLuminance = exp2(gLuminanceTex.SampleLevel(gLuminanceTexSampler, texC, kLuminanceLod).r);
    float pixelLuminance = calcLuminance(finalColor);
    finalColor *= (kExposureKey / avgLuminance);
#endif
*/
    if(gParams.autoExposure)
    {
        // apply auto exposure

#ifndef TONEMAPPING_AUTOEXPOSURE_CPU
#error this must be defined
#elif TONEMAPPING_AUTOEXPOSURE_CPU == 1
        float avgLuminance = gParams.avgLuminance;
#else
        float avgLuminance = exp2(gLuminanceTex.SampleLevel(gLuminanceTexSampler, texC, kLuminanceLod).r);
#endif
        float pixelLuminance = calcLuminance(finalColor);

        finalColor *= clamp( (kExposureKey / avgLuminance), gParams.autoExposureLumValueMin, gParams.autoExposureLumValueMax );
    }

    if (gParams.enabled)
    {
        // apply color grading
        finalColor = mul(finalColor, (float3x3) gParams.colorTransform);

        // apply tone mapping
        finalColor = toneMap(finalColor);

        // CameraLut normally replaces the selected operator. For calibration
        // workflows it can instead correct the selected operator's output.
        if (gParams.applyCameraLutAfterToneMap)
            finalColor = toneMapCameraLut(finalColor);

        if (gParams.clamped)
            finalColor = saturate(finalColor);
    }

    return float4(finalColor, color.a);
}

#endif //__TONE_MAPPING_PS_HLSLI__
